# Generated by Django 5.0.8 on 2024-08-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "a_rtchat",
            "0002_rename_body_groupmessage_content_chatgroup_creat_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="receiption",
            old_name="message_id",
            new_name="message",
        ),
        migrations.RemoveField(
            model_name="receiption",
            name="author",
        ),
        migrations.AlterField(
            model_name="blocks",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
