# Generated by Django 5.0.8 on 2024-08-26 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_rtchat", "0005_alter_chatgroup_users_online"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receiption",
            old_name="user",
            new_name="user_id",
        ),
    ]
