# Generated by Django 5.0.8 on 2024-08-26 14:04

import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_rtchat", "0008_chatgroup_is_private_chatgroup_members_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatgroup",
            name="groupname",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="chatgroup",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="chat_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
